#!/usr/bin/env bash

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

. "$SCRIPT_DIR/../lib/print"

icon_dir="$HOME/Pictures/icons"
wallpapers_dir="$HOME/Pictures/wallpapers"

mkdir -p "$icon_dir"
mkdir -p "$wallpapers_dir"

cp "$SCRIPT_DIR/../assets/icons/screenshot.png" "$icon_dir"
cp "$SCRIPT_DIR/../assets/icons/backup.png" "$icon_dir"
cp "$SCRIPT_DIR/../assets/icons/password-key.png" "$icon_dir"

shopt -s nullglob nocaseglob
wallpapers=("$SCRIPT_DIR/../assets/wallpapers"/*.{jpg,jpeg,png,webp})
shopt -u nullglob nocaseglob

cp "${wallpapers[@]}" "$wallpapers_dir"

print_step Done
