# Taps
tap "homebrew/autoupdate"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "neovim/neovim"

# Desktop tools
cask "1password"
cask "firefox"
cask "kitty"
cask "rectangle-pro"
cask "spotify"
cask "gimp"

# Communication
cask "discord"
cask "slack"

# CLI tools
brew "macvim"
brew "wget"
brew "spotify-tui"
cask "docker"
brew "docker-compose"
brew "lazygit"
brew "node"
brew "angular-cli"
brew "azure-cli"
brew "k9s"
brew "jq"
brew "fd"
brew "kubeseal"
brew "luarocks"
brew "maven"
brew "neovim", args: ["HEAD"]
brew "ripgrep"

# Terminal stuff
brew "fish"
brew "tmux"
brew "tree"
brew "watch"

# Fonts
cask "font-fira-code"
cask "font-fira-code-nerd-font"
cask "font-hack-nerd-font"

# Formatters
brew "eslint"
brew "google-java-format"
brew "semgrep"
brew "stylua"

# Build tools
brew "python@3.9"
brew "cmake"
brew "ctags"
brew "go"
brew "openjdk@17"
brew "openssl@3", link: true
brew "pkg-config"
brew "yarn"
