[indicator]
parent = { fg = "#ffffff", bg = "#ff4f9a" }
current = { fg = "#ffffff", bg = "#ff4f9a" }
preview = { fg = "#ff4f9a" }
padding = { open = " ", close = " " }

[filetype]
rules = [{ url = "*/", fg = "#999999" }]
