#!/usr/bin/env bash

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

. "$SCRIPT_DIR/../lib/print"
. "$SCRIPT_DIR/../lib/firefox"

profile_dir=$(get_active_profile_dir "$HOME/.config/librewolf/librewolf")

theme_repo="$HOME/.repos/librewolf-theme"

if [[ ! -d "$theme_repo" ]]; then
    gum spin --spinner line --title "Cloning cascade repository to '$theme_repo'" -- \
        git clone https://github.com/cascadefox/cascade.git "$theme_repo"
else
    gum spin --spinner line --title "Updating theme repo '$theme_repo'" -- \
        git -C "$theme_repo" pull
fi

rm -rf "$profile_dir/chrome/"

cp -r "$theme_repo/chrome/" "$profile_dir/"

print_step Done
