#!/usr/bin/env bash
if ! command -v pacman &>/dev/null; then
    source /etc/os-release
    echo "These dotfiles are written for Arch-based systems; you're on ${PRETTY_NAME:-$ID}"
    exit 1
fi

if ! command -v gum >/dev/null 2>&1; then
  sudo pacman -Sy --noconfirm gum &> /dev/null
fi

red="#ef4444"
pink="#e1579c"

gum style --foreground $pink --bold --underline "Running setup for dotfiles"

printf "\nThis script will setup some basic things before being able to run the apply script.\n"
printf "\nThis script only needs to be run once.\n"

if [ -d "$HOME/dotfiles" ]; then
    gum style --foreground $pink "~/dotfiles already exists — skipping clone"
else
    gum style --foreground $pink "Cloning dotfiles..."
    git clone https://github.com/Rahmerh/dotfiles.git ~/dotfiles
fi

gum style --foreground $pink "Please input info for your global git config:"

name="$(gum input --prompt "User name: ")" || exit 1
[ -z "$name" ] && { gum style --foreground $red "Name cannot be empty"; exit 1; }

email="$(gum input --prompt "Email: " --placeholder "you@example.com")" || exit 1
[ -z "$email" ] && { gum style --foreground $red "Email cannot be empty"; exit 1; }

git config --global user.name "$name"
git config --global user.email "$email"

gum style --foreground $pink "Done! Run ~/dotfiles/apply to apply dotfiles."
