#!/usr/bin/env bash

source $HOME/.config/sketchybar/settings/colors
source $HOME/.config/sketchybar/settings/fonts

BATTERY='
# Colors
source $HOME/.config/sketchybar/settings/colors
source $HOME/.config/sketchybar/settings/fonts
BATT_PERCENT=$(pmset -g batt | grep -Eo "\d+%" | cut -d% -f1)
CHARGING=$(pmset -g batt | grep "AC Power")
if [[ $CHARGING != "" ]]; then
    sketchybar -m --set battery \
        icon.color=${GREEN} \
        icon= \
        label=$(printf "${BATT_PERCENT}%%")
    exit 0
fi
[[ "${BATT_PERCENT}" -gt 10 ]] && COLOR="${WHITE}" || COLOR="${RED}"
case ${BATT_PERCENT} in
    100) ICON="" ;;
    9[0-9]) ICON="" ;;
    8[0-9]) ICON="" ;;
    7[0-9]) ICON="" ;;
    6[0-9]) ICON="" ;;
    5[0-9]) ICON="" ;;
    4[0-9]) ICON="" ;;
    3[0-9]) ICON="" ;;
    2[0-9]) ICON="" ;;
    1[0-9]) ICON="" ;;
    *) ICON=""
esac
sketchybar -m --set battery \
    icon.color="$COLOR" \
    icon.font="$DEFAULT_FONT" \
    icon="$ICON" \
    label=$(printf "${BATT_PERCENT}%%") \
    label.font="$DEFAULT_FONT"
'

sketchybar -m --add item battery right \
              --set battery update_freq=3 \
              script="$BATTERY" \
              icon="" \
              icon.padding_left=10 \
              icon.font="$DEFAULT_FONT" \
              label.padding_left=10 \
              label.padding_right=10 \
              background.padding_right=20 \
              background.color=$BACKGROUND_GRAY \
              background.border_color=$WHITE \
              background.border_width=1
