#!/usr/bin/env sh

source $HOME/.config/sketchybar/settings/fonts
source $HOME/.config/sketchybar/settings/colors

sketchybar --add item sound right \
    --set sound \
    update_freq=5 \
    icon.color=$WHITE \
    icon.font="$DEFAULT_FONT" \
    icon.padding_left=10 \
    background.color=$BACKGROUND_GRAY \
    background.border_color=$WHITE \
    background.border_width=1 \
    background.padding_right=20 \
    label.font="$DEFAULT_FONT" \
    label.padding_right=10 \
    script="~/.config/sketchybar/plugins/sound"
