#!/usr/bin/env bash

source $HOME/.config/sketchybar/settings/colors

SCRIPT='
WINDOW_TITLE=$(/opt/homebrew/bin/yabai -m query --windows --window | jq -r ".title")
if [[ $WINDOW_TITLE = "" ]]; then
    WINDOW_TITLE=$(/opt/homebrew/bin/yabai -m query --windows --window | jq -r ".app")
fi
if [[ ${#WINDOW_TITLE} -gt 50 ]]; then
    WINDOW_TITLE=$(echo "$WINDOW_TITLE" | cut -c 1-50)
    sketchybar -m --set title label="$WINDOW_TITLE"…
    exit 0
fi
sketchybar -m --set title label="$WINDOW_TITLE"
'

sketchybar -m --add event yabai_window

sketchybar -m --add item title left \
              --subscribe title yabai_window \
              --set title script="$SCRIPT" \
                icon.padding_left=15 \
                label.padding_right=15 \
                background.color=$BACKGROUND_GRAY \
                background.padding_left=0 \
                background.padding_right=20 \
                background.border_color=$WHITE \
                background.border_width=1
