#!/usr/bin/env bash

source $HOME/.config/sketchybar/plugins/wifi
source $HOME/.config/sketchybar/settings/colors
source $HOME/.config/sketchybar/settings/fonts

WIFI_ICN=

sketchybar -m --add item wifi.control right \
    --set wifi.control icon=$WIFI_ICN \
    label.drawing=off \
    icon.padding_left=10 \
    icon.padding_right=10 \
    icon.font="$DEFAULT_FONT" \
    label.padding_right=15 \
    label.padding_left=10 \
    background.color=$BACKGROUND_GRAY \
    background.border_color=$WHITE \
    background.border_width=1 \
    background.padding_right=20 \
    click_script="$POPUP_CLICK_SCRIPT" \
    popup.background.color=0x70000000 \
    popup.blur_radius=50 \
    popup.background.border_color=$WHITE \
    popup.background.border_width=1 \
    popup.height=20 \
    popup.y_offset=10 \
    --add item wifi.ssid popup.wifi.control \
    --set wifi.ssid icon= \
    label="${SSID}" \
    label.padding_left=5 \
    label.padding_right=5 \
    label.font="$DEFAULT_FONT" \
    icon.font="$DEFAULT_FONT" \
    icon.padding_left=10 \
    --add item wifi.speed popup.wifi.control \
    --set wifi.speed icon= \
    label.padding_left=5 \
    label.padding_right=5 \
    label.font="$DEFAULT_FONT" \
    icon.font="$DEFAULT_FONT" \
    icon.padding_left=10 \
    script="$HOME/.config/sketchybar/plugins/wifi_click" \
    update_freq=10 \
