#!/usr/bin/env bash

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

. "$SCRIPT_DIR/../lib/print"

for group in plugdev openrazer docker; do
    getent group "$group" >/dev/null || sudo groupadd "$group"

    if ! id -nG "$USER" | grep -qw "$group"; then
        sudo usermod -aG "$group" "$USER"
    fi
done

print_step Done
