#!/usr/bin/env bash

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

. "$SCRIPT_DIR/../lib/print"

sudo systemctl daemon-reload

if [[ -f "/etc/systemd/system/backup-system.timer" ]]; then
    sudo systemctl enable --now /etc/systemd/system/backup-system.timer >/dev/null
fi

print_step Done
