#!/usr/bin/env bash

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

. "$SCRIPT_DIR/../lib/print"

sudo systemctl daemon-reload

if [[ -f "/etc/systemd/system/backup-system.timer" ]]; then
    sudo systemctl enable --now backup-system.timer
fi

if ! systemctl is-enabled --quiet greetd.service; then
    sudo systemctl enable greetd.service
fi

print_step Done
