#!/usr/bin/env bash

sketchybar --bar position=top \
    height=20 \
    shadow=off \
    display=all \
    color="0x00000000" \
    y_offset=10 \
    --default \
    icon.font="Hack Nerd Font:Bold:18.0"
