#!/usr/bin/env bash

source $HOME/.config/sketchybar/settings/colors

sketchybar --bar position=top \
    height=20 \
    shadow=off \
    display=all \
    color=$INVISIBLE \
    --default \
    icon.font="Hack Nerd Font:Bold:18.0"
