#!/usr/bin/env bash

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

. "$SCRIPT_DIR/../lib/print"
. "$SCRIPT_DIR/../lib/prefs"
. "$SCRIPT_DIR/../lib/wine"

if ! command -v yay &>/dev/null; then
    sudo pacman -S --needed git base-devel --noconfirm

    temp_dir=$(mktemp -d)

    git clone https://aur.archlinux.org/yay.git "$temp_dir"

    cd "$temp_dir" || exit 1

    makepkg -si

    yay -Y --gendb --noconfirm
    yay -Syu --devel --noconfirm
    yay -Y --devel --save --noconfirm
fi

cli_packages=(
    neovim
    kitty
    bat
    eza
    fzf
    fd
    ripgrep
    jq
    stow
    tealdeer
    fastfetch
    yazi
    lazygit
    lazydocker
    httpie
    lazysql
    systemctl-tui
)

system_packages=(
    curl
    pv
    gnupg
    wireguard-tools
    ufw
    rsync
    jmtpfs
    cifs-utils
    croc
)

media_packages=(
    7zip
    wine
    winetricks
    imagemagick
    ffmpeg
    bc
    pastel
    xmlstarlet
    wl-clipboard
    wf-recorder
    wl-mirror
    wiremix
    playerctl
    libnotify
    mpv
)

gui_packages=(
    firefox
    rofi
    feh
    nvidia-container-toolkit
    pinta
    ripdrag
    waybar
    spotify
)

wm_packages=(
    niri
    gnome-keyring
    python
    swaybg
    wired
    grim
    slurp
    xdg-desktop-portal
    xdg-desktop-portal-gnome
    xdg-desktop-portal-termfilechooser-hunkyburrito-git
    xorg-xrandr
    xwayland-satellite
    hypridle
    hyprlock
    sddm
    qt6-5compat
    qt6-imageformats
)

font_packages=(
    ttf-jetbrains-mono-nerd
    ttf-cascadia-code-nerd
)

dev_packages=(
    bun
    bash-language-server
    shfmt
    typescript
    typescript-language-server
    vue-language-server
    vscode-css-languageserver
    vscode-html-languageserver
    vscode-json-languageserver
    cspell-lsp
    shellcheck
    qt5-tools
    luarocks
    lua-language-server
    docker
    docker-buildx
    docker-compose
    clang
    rust
    rust-analyzer
    codelldb-bin
    android-tools
)

desktop_packages=(
    openrazer-meta
    gamemode
    discord
    steam
    razer-cli
    openrgb
)

laptop_packages=(
    logiops
    blueman
)

if mt_is_laptop; then
    mt_packages=("${laptop_packages[@]}")

    if ! systemctl is-enabled --quiet logid.service; then
        sudo systemctl enable --now logid.service
    fi
elif mt_is_desktop; then
    mt_packages=("${desktop_packages[@]}")
else
    print_error "Unknown machine type"
    exit 1
fi

install_packages() {
    local package
    local repo_package
    local -A repo_package_names=()
    local repo_packages=()
    local aur_packages=()

    print_step "Mapping AUR packages"
    while IFS= read -r repo_package; do
        repo_package_names["$repo_package"]=1
    done < <(pacman -Slq)

    for package in "$@"; do
        if [[ -v "repo_package_names[$package]" ]]; then
            repo_packages+=("$package")
        else
            aur_packages+=("$package")
        fi
    done

    if ((${#repo_packages[@]})); then
        print_step "Installing/updating repository packages"
        sudo pacman --needed -S --noconfirm "${repo_packages[@]}"
    fi

    for package in "${aur_packages[@]}"; do
        print_step "Reviewing AUR package: $package"
        yay --aur --needed -S \
            --diffmenu \
            --answerdiff All \
            --confirm \
            "$package"
    done
}

install_packages \
    "${cli_packages[@]}" \
    "${system_packages[@]}" \
    "${media_packages[@]}" \
    "${gui_packages[@]}" \
    "${font_packages[@]}" \
    "${dev_packages[@]}" \
    "${wm_packages[@]}" \
    "${mt_packages[@]}"

print_step "Installing manual packages"

if ! command -v pass-cli &>/dev/null; then
    curl -fsSL https://proton.me/download/pass-cli/install.sh | bash
fi

cargo install --locked tree-sitter-cli
cargo install --locked zoxide
cargo install gpu-usage-waybar
cargo install cargo-edit
cargo install sax
cargo install --git https://github.com/webstonehq/tuxedo

if ! dotnet tool list --global | awk '{ print $1 }' | grep -qx easydotnet; then
    dotnet tool install --global EasyDotnet
fi

if ! dotnet tool list --global | awk '{ print $1 }' | grep -qx csharpier; then
    dotnet tool install --global CSharpier
fi

print_step "Installing yazi plugins"

/usr/bin/ya pkg install

print_step "Installing apps in wine"

if mt_is_desktop; then
    install_package_in_cache dotnet48
    install_package_in_cache vcrun2022
    install_package_in_cache corefonts

    # Mod organizer 2
    install_package_from_cache dotnet48 modorganizer
    install_package_from_cache vcrun2022 modorganizer
    install_package_from_cache corefonts modorganizer

    install_exe_in_app "https://aka.ms/vs/17/release/vc_redist.x64.exe" "vc_redistx64_installer.exe" modorganizer

    install_wine_app modorganizer ModOrganizer2/modorganizer
fi

print_step Done
