#!/usr/bin/env bash

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

. "$SCRIPT_DIR/../lib/print"
. "$SCRIPT_DIR/../lib/machine-type"

force_stow() {
    local target="$1"
    local package="$2"
    local use_sudo="${3:-0}"

    local stow_cmd=()

    if (( use_sudo )); then
        stow_cmd+=(sudo)
    fi

    stow_cmd+=(stow --target="$target" "$package")

    base_dir="$(pwd)/$package"

    mapfile -d '' files < <(find "$base_dir" -type f -print0)

    for entry in "${files[@]}"; do
        local expected="$target${entry/$base_dir/}"

        local expected_dirname=$(dirname "$expected")

        # Create all parent dirs if not exists, to only symlink files.
        if [[ ! -d "$expected_dirname" ]]; then
            if (( use_sudo )); then
                sudo mkdir -p "$expected_dirname"
            else
                mkdir -p "$expected_dirname"
            fi
        fi

        if [[ -L "$expected" ]]; then
            # TODO: Check if symlink to dotfiles or not. Prompt to delete if not.
            continue;
        elif [[ -f "$expected" ]]; then
            if (( use_sudo )); then
                sudo rm "$expected"
            else
                rm "$expected"
            fi
        fi
    done

    print_step "Stowing $package"
    "${stow_cmd[@]}"
}

force_stow "$HOME" home 0

cd system

force_stow / greetd 1
force_stow / sysctl 1

if mt_is_personal; then
    force_stow / system-backup 1
fi

if mt_is_work; then
    force_stow / logid 1
fi

print_step "Done"
