#!/usr/bin/env bash

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

. "$SCRIPT_DIR/../lib/print"
. "$SCRIPT_DIR/../lib/prefs"

sudo systemctl daemon-reload

if ! systemctl is-enabled --quiet sddm.service; then
    sudo systemctl enable sddm.service
fi

systemctl --user daemon-reload

if ! systemctl --user is-enabled --quiet proton-pass-ssh-agent.service; then
    systemctl --user enable --now proton-pass-ssh-agent.service
fi

if ! systemctl --user is-enabled --quiet proton-pass-sync.timer; then
    systemctl --user enable --now proton-pass-sync.timer
fi

print_step Done
