#!/usr/bin/env sh

# General settings
sh ~/.config/sketchybar/settings/defaults

# Left items
sh ~/.config/sketchybar/items/spotify

# Right items
sh ~/.config/sketchybar/items/battery
sh ~/.config/sketchybar/items/wifi

# Finalizing setup
sketchybar --update

echo "sketchybar configuation loaded.."
