#!/usr/bin/env sh

PLUGIN_DIR="$HOME/.config/sketchybar/plugins"
# https://github.com/shahmilav/carbonfiber-dots/tree/main/sketchybar

# General settings
sh ~/.config/sketchybar/settings/defaults

# Right items
sh ~/.config/sketchybar/items/battery
sh ~/.config/sketchybar/items/wifi

# Finalizing setup
sketchybar --update

echo "sketchybar configuation loaded.."
