#!/usr/bin/env sh

FONT="Hack Nerd Font"

# General settings
sh ~/.config/sketchybar/settings/defaults

# Right items
sh ~/.config/sketchybar/items/battery

# Finalizing setup
sketchybar --update

echo "sketchybar configuation loaded.."
