#!/usr/bin/env bash

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

. "$SCRIPT_DIR/../lib/print"

profile_dir="$HOME/.mozilla/firefox/default/"

if [[ ! -d "$profile_dir" ]]; then
    mkdir -p "$profile_dir"
fi

install_extension() {
    local extension_name=$1

    local extensions_dir="$profile_dir/extensions"
    mkdir -p "$extensions_dir"

    local installed_extensions_file="$profile_dir/extensions/.installed"

    [[ -f "$installed_extensions_file" ]] || touch "$installed_extensions_file"

    if grep -q "$extension_name" "$installed_extensions_file"; then
        print_warning "$extension_name already installed, skipping"
        return 0
    fi

    local tmp_file=$(mktemp)

    curl -sLo "$tmp_file" "https://addons.mozilla.org/firefox/downloads/latest/$extension_name/latest.xpi"

    local external_id=$(unzip -p "$tmp_file" manifest.json | jq -r '.browser_specific_settings.gecko.id')

    if [[ -z "$external_id" ]]; then
        print_error "Could not extract external id from $extension_name, skipping"
        return 1
    fi

    mv "$tmp_file" "$extensions_dir/$external_id.xpi"

    print_step "Installed $extension_name"

    echo "$extension_name" >> "$installed_extensions_file"
}

install_extension sponsorblock
install_extension return-youtube-dislikes
install_extension control-panel-for-youtube
install_extension proton-pass
install_extension ublock-origin

print_step Done
