#!/usr/bin/env bash

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

. "$SCRIPT_DIR/../lib/print"

sudo nvidia-ctk runtime configure --runtime=docker &>/dev/null

if ! systemctl is-enabled --quiet docker.service; then
    sudo systemctl enable --now docker.service
fi

print_step Done
