#!/usr/bin/env bash

export XDG_CONFIG_HOME="$HOME/.config"

export VISUAL=nvim
export EDITOR=nvim

export MANPAGER="bat -plman"
export LIBDECOR_DISABLE=1

export CHROME_EXECUTABLE=/usr/bin/google-chrome-stable
export DOCKER_BUILDKIT=1
export PROTON_PASS_LINUX_KEYRING=dbus
export SSH_AUTH_SOCK="$HOME/.ssh/proton-pass-agent.sock"

export MCFLY_LIGHT=FALSE
export MCFLY_KEY_SCHEME=vim
export MCFLY_FUZZY=2
export MCFLY_RESULTS=20
export MCFLY_DELETE_WITHOUT_CONFIRM=false
export MCFLY_INTERFACE_VIEW=TOP
export MCFLY_DISABLE_MENU=FALSE
export MCFLY_PROMPT="❱"

path_add() {
    case ":$PATH:" in
        *":$1:"*) ;;
        *) PATH="$1:$PATH" ;;
    esac
}

path_add "$HOME/.pub-cache/bin"
path_add "$HOME/go/bin"
path_add "$HOME/.cargo/bin"
path_add "$HOME/.local/bin"
path_add "$HOME/.fvm_flutter/bin"
path_add "$HOME/.dotnet/tools"

unset -f path_add
