#!/bin/bash
# Script is modified version of the project's README: https://github.com/GloriousEggroll/proton-ge-custom?tab=readme-ov-file#installation

set -euo pipefail

DEBUG=false

while test $# != 0
do
    case "$1" in
    -d) 
        DEBUG=true
        ;;
    *)  usage ;;
    esac
    shift
done

echo "Installing/updating custom proton GE."

STEAM_PROTON_FOLDER="/home/bas/.steam/root/compatibilitytools.d"

if [ -d /tmp/proton-ge-custom ]; then
    sudo rm -rf /tmp/proton-ge-custom
fi

mkdir /tmp/proton-ge-custom
cd /tmp/proton-ge-custom

if ! [ -d "$STEAM_PROTON_FOLDER" ]; then
    mkdir -p ~/.steam/root/compatibilitytools.d
fi

CURRENT_VERSION=$(ls -Art "$STEAM_PROTON_FOLDER" | tail -1)

VERSION_TO_INSTALL=$(curl -sI https://github.com/GloriousEggroll/proton-ge-custom/releases/latest | awk -F '/' '/^location/ {print  substr($NF, 1, length($NF)-1)}')

if [ "$DEBUG" = true ]; then
    echo "DEBUG - Current version: $CURRENT_VERSION" 
    echo "DEBUG - Version to install: $VERSION_TO_INSTALL" 
fi

if [ "$VERSION_TO_INSTALL" == "$CURRENT_VERSION" ]; then
    echo "Nothing to do, latest version of proton GE ($VERSION_TO_INSTALL) already installed. Exiting."
    exit 0
fi

read -p "New version available ($VERSION_TO_INSTALL), install now? (y/n)" -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
    echo "Downloading tarball"
    curl -sLOJ "$(curl -s https://api.github.com/repos/GloriousEggroll/proton-ge-custom/releases/latest | grep browser_download_url | cut -d\" -f4 | grep .tar.gz)"
    echo "Done"

    echo "Downloading checksum"
    curl -sLOJ "$(curl -s https://api.github.com/repos/GloriousEggroll/proton-ge-custom/releases/latest | grep browser_download_url | cut -d\" -f4 | grep .sha512sum)"
    echo "Done"

    sha512sum -c ./*.sha512sum

    echo "Extracting tarball"
    tar -xf GE-Proton*.tar.gz -C "$STEAM_PROTON_FOLDER"

    echo "Latest proton GE ($VERSION_TO_INSTALL) installed."
else
    echo "Cancelling update"
fi
