general {
    disable_loading_bar = true
    hide_cursor = false
}

background {
    path = ~/Pictures/wallpaper.jpg
    blur_passes = 2
    blur_size = 6
}

shape {
    monitor =
    size = 10, 70
    color = rgb(e1579c)
    rounding = 0

    position = 40, 5%
    halign = left
    valign = bottom
    zindex = 1
}

input-field {
    monitor =
    size = 420, 70

    inner_color = rgba(0,0,0,0.65)
    font_color = rgb(ffffff)

    outline_thickness = 0
    rounding = 0

    position = 40, 5%
    halign = left
    valign = bottom

    dots_center = false
    fade_on_empty = false
    placeholder_text =
}
