return {
	kind = {
		Text = "",
		Method = "",
		Function = "",
		Constructor = "",
		Field = "",
		Variable = "",
		Class = "",
		Interface = "",
		Module = "",
		Property = "",
		Unit = "",
		Value = "",
		Enum = "",
		Keyword = "",
		Snippet = "",
		Color = "",
		File = "",
		Reference = "",
		Folder = "",
		EnumMember = "",
		Constant = "",
		Struct = "",
		Event = "",
		Operator = "",
		TypeParameter = "",
	},
	documents = {
		File = "",
		SearchFile = "",
		Files = "",
		Folder = "",
		OpenFolder = "",
		EmptyFolder = "",
		EmptyOpenFolder = "",
		FolderSymlink = "",
		Textbox = "﬍",
	},
	git = {
		Add = "",
		Mod = "",
		Remove = "",
		Rename = "",
		Diff = "",
		Repo = "",
		Octoface = "",
		Branch = "",
		FileChanged = "",
		FileStaged = "",
		FileUntracked = "",
		FileUnmerged = "",
		FileIgnored = "",
		FileRenamed = "ﱴ",
	},
	ui = {
		FatArrowClosed = "▸",
		FatArrowOpen = "▾",
		Close = "",
		Bug = "",
		Telescope = "",
		Gears = "",
		Symlink = "",
		List = "",
		ArrowRight = "﬌",
	},
	diagnostics = {
		Error = "",
		Warning = "",
		Information = "",
		Question = "",
		Hint = "",
	},
	debugging = {
		Breakpoint = " ",
	},
}
